/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package package1;
import java.awt.Color;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.Statement;
/**
 *
 * @author alyss
 */
public class frameMain extends javax.swing.JFrame {
    static Connection connection;
    static String url;
    static Statement st;
    static ResultSet rs;
     public int search(String id,String name)
   throws SQLException, ClassNotFoundException{
    Class .forName("com.mysql.jdbc.Driver");
    url="jdbc:mysql://localhost:3306/isdbfinal";
    connection = DriverManager.getConnection
    (url, "root","Hellojavawela11");
    st = connection.createStatement();
    rs=st.executeQuery
    ("Select * From reg_tbl Where id= '"+id+"'  "
            + "and fname = '" +name+ "'");
            if(rs!=null){
                return 1;
            }
            else{
                return 0;
            }

     }
    /**
     * Creates new form frameMain
     */
    public frameMain() {
        initComponents();
        frameMain.this.setLocation(400,180);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Save = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        textPass = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textEmail = new javax.swing.JTextField();
        textMobileNum = new javax.swing.JTextField();
        textAddress = new javax.swing.JTextField();
        textLast = new javax.swing.JTextField();
        textName = new javax.swing.JTextField();
        textId = new javax.swing.JTextField();
        Cancel = new javax.swing.JButton();
        Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel1.setText("INFORMATION");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel1)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 50));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(255, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 204));
        jLabel3.setText("First Name:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 80, -1));

        Save.setBackground(new java.awt.Color(0, 153, 51));
        Save.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Save.setForeground(new java.awt.Color(255, 255, 204));
        Save.setText("Save");
        Save.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        jPanel2.add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 80, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 204));
        jLabel8.setText("Password:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 80, -1));

        textPass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(textPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 150, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 204));
        jLabel7.setText("E-mail:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 80, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 204));
        jLabel6.setText("Mobile No.:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 80, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 204));
        jLabel5.setText("Address:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 80, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 204));
        jLabel4.setText("Last Name:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 80, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 204));
        jLabel2.setText("User ID:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 80, -1));

        textEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(textEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 150, -1));

        textMobileNum.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(textMobileNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 150, -1));

        textAddress.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(textAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 150, -1));

        textLast.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(textLast, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 150, -1));

        textName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(textName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 150, -1));

        textId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(textId, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 150, -1));

        Cancel.setBackground(new java.awt.Color(204, 0, 0));
        Cancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Cancel.setForeground(new java.awt.Color(255, 255, 204));
        Cancel.setText("Cancel");
        Cancel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        jPanel2.add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, 80, -1));

        Back.setBackground(new java.awt.Color(255, 255, 204));
        Back.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Back.setText("Back");
        Back.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel2.add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 90, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 340, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        int check=0;
        try {
            check = search(textId.getText(),
                    textName.getText());
        } catch (SQLException ex) {
           // Logger.getLogger(frameRegister.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            //Logger.getLogger(frameRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
if(check==1){
   try {
      if(textPass.getText() == null ?
        "" == null : textPass.getText().equals("")){
        JOptionPane.showMessageDialog(null, 
        "Password must contain value","System Message",
                JOptionPane.INFORMATION_MESSAGE);
        textAddress.setText(null);
        textId.setText(null);
        textName.setText(null);
        textMobileNum.setText(null);
        textLast.setText(null);
        textPass.setText(null);
        textEmail.setText(null);
        }
  if((textId.getText() == null ? "" == null :
      textId.getText().equals("")) ||
      (textName.getText() == null ? "" == null :
      textName.getText().equals(""))){
      JOptionPane.showMessageDialog(null, 
      "ID and Name is Required","System Message",
              JOptionPane.ERROR_MESSAGE);
                }
                else{
                    st.executeUpdate("Insert into reg_tbl("
                   + "id,fname,lname,address,mobileno,email,"
                            + "password" + ") VALUES ('"
                            + textId.getText() + "','"
                            + textName.getText() + "','"
                            + textLast.getText() + "','"
                            + textAddress.getText() + "','"
                            + textMobileNum.getText() + "','"
                            + textEmail.getText() + "','"
                            +textPass.getText()+  "')");
                    JOptionPane.showMessageDialog(null, "Record Created",
                            "System Message",JOptionPane.INFORMATION_MESSAGE);
                    frameMain.this.setVisible(false);
                    textId.setText("");
                }
            } catch (SQLException ex) {
               // Logger.getLogger(frameMain.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, 
                        "Record Already Exist","System Message",
                        JOptionPane.ERROR_MESSAGE);
            textAddress.setText(null);
            textId.setText(null);
            textName.setText(null);
            textMobileNum.setText(null);
            textLast.setText(null);
            textEmail.setText(null);
            textPass.setText(null);
            }

        }
    }//GEN-LAST:event_SaveActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        System.exit(0);
    }//GEN-LAST:event_CancelActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        
        Login page = new Login();
                page.setVisible(true);
                setVisible(false);
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField textAddress;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textId;
    private javax.swing.JTextField textLast;
    private javax.swing.JTextField textMobileNum;
    private javax.swing.JTextField textName;
    private javax.swing.JPasswordField textPass;
    // End of variables declaration//GEN-END:variables
}
